<?php

namespace AppBundle\Repository;

/**
 * SongRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SongRateRepository extends \Doctrine\ORM\EntityRepository
{
}
