<?php

namespace AppBundle\Repository;

/**
 * UserRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRateRepository extends BaseRepository
{
}
