security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_USER
      - ROLE_NEWS

    ROLE_NEWS: [ROLE_NEWS_NEW, ROLE_NEWS_EDIT, ROLE_NEWS_DELETE]

    ROLE_USER: [ROLE_COMMENT]
    ROLE_COMMENT: [ROLE_COMMENT_NEW, ROLE_COMMENT_EDIT, ROLE_COMMENT_DELETE]

