###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

mysql-server:
  image:  mysql/mysql-server:latest
  container_name: mysql-server
  volumes:
    - mysql_data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 'mysqlrootpassword'
    MYSQL_ROOT_HOST: '%'
  ports:
    - "3306:3306"

postgres-server:
  image: postgres:latest
  container_name: postgres-server
  volumes:
    - postgres_data:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
  ports:
    - "5433:5432"

mds-memcached:
  image: phpdockerio/memcached:latest
  container_name: mds-memcached

icecast:
  image: moul/icecast:latest
  container_name: icecast
  volumes:
  - logs:/var/log/icecast2
  - /etc/localtime:/etc/localtime:ro
  environment:
  - ICECAST_SOURCE_PASSWORD=changeme
  - ICECAST_ADMIN_PASSWORD=changeme
  - ICECAST_PASSWORD=changeme
  - ICECAST_RELAY_PASSWORD=changeme
  ports:
  - 8001:8000

mpd:
  image: vimagick/mpd
  container_name: mpd
  ports:
    - "6600:6600"
    - "8800:8800"
  volumes:
#    - ./mpd/mpd.conf:/etc/mpd.conf
    - ./mpd/music:/var/lib/mpd/music
    - ./playlists:/var/lib/mpd/playlists
  devices:
    - /dev/snd
  restart: always

#mds-rabbitmq:
#  image: rabbitmq:latest
#  container_name: mds-rabbitmq
#  hostname: "mds-rabbitmq"
#  environment:
#    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
#    RABBITMQ_DEFAULT_USER: "rabbitmq"
#    RABBITMQ_DEFAULT_PASS: "rabbitmq"
#    RABBITMQ_DEFAULT_VHOST: "/"
#  ports:
#    - "15672:15672"
#    - "5672:5672"
#  labels:
#    NAME: "mds-rabbitmq"
#  volumes:
#      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

#mds-mongo:
#  image: mongo:latest
#  container_name: mds-mongo
#  ports:
#     - "27018:27017"

mds-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: mds-php-fpm
  volumes:
    - ..:/var/www/mds
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
    - ./php-fpm/start.sh:/start.sh
    - /tmp/:/tmp/
  links:
    - mds-memcached
    - mysql-server
    - postgres-server
#    - mds-rabbitmq
#  env_file:
#    - ./php-fpm/xdebug-cli.env

mds-nginx:
  image: phpdockerio/nginx:latest
  container_name: mds-nginx
  volumes:
      - ..:/var/www/mds
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "80:80"
  links:
   - mds-php-fpm